// This play book can be used to roll out exclusions for MDATP for Linux agents
// mdatp_managed.json need to be updated with respective changes and validated before rolling out the file

- hosts: <your host group name>
  become: true
  gather_facts: false
  tasks:
   - name: Checking for existing mdatp_managed.json
     stat: 
      path: /etc/opt/microsoft/mdatp/managed/mdatp_managed.json
     register: mdatp_managed
     
   - name: Deleting existing mdatp_managed.json
     file:
      path: /etc/opt/microsoft/mdatp/managed/mdatp_managed.json
      state: absent
     when: mdatp_managed.stat.exists
       
   - name: Copying new configuration file into /etc/opt/microsoft/mdatp/managed/
     copy:
      src: /etc/ansible/files/mdatp_managed.json
      dest: /etc/opt/microsoft/mdatp/managed/
      mode: 0600
      owner: root
      group: root
     
   - name: Restarting MDATP service
     shell: systemctl restart mdatp
