// This role is used to setup the Microsoft prod repo prior to installing the MDATP agent on Linux
// Download and place the below files in /etc/ansible/files
// Microsoft GPG Public Key - https://packages.microsoft.com/keys/microsoft.asc
// Microsoft Prod repository (RHEL 7.4) - https://packages.microsoft.com/config/rhel/7.4/packages-microsoft-prod.rpm

- name: Copying Microsoft GPG key
  copy:
   src: /etc/ansible/files/microsoft.asc
   dest: /tmp
   mode: 0755
   owner: root
   group: root

- name: Installing Microsoft GPG key
  yum:
   name: /tmp/microsoft.asc
   state: present

- name: Copying Microsoft Prod repository for RHEL 7
  copy:
   src: /etc/ansible/files/packages-microsoft-prod.rpm
   dest: /tmp
   mode: 0755
   owner: root
   group: root
   
- name: Installing Microsoft Prod repository for RHEL 7
  yum:
   name: /tmp/packages-microsoft-prod.rpm
   state: present
