// Following role can be used to roll out the exclusions for MDATP for Linux
// Make the respective changes in mdatp_managed.json file you want to roll out and place it in /etc/ansible/files/

- name: Checking for existing mdatp_managed.json
  stat: 
   path: /etc/opt/microsoft/mdatp/managed/mdatp_managed.json
  register: mdatp_managed
  
- name: Deleting existing mdatp_managed.json
  file:
   path: /etc/opt/microsoft/mdatp/managed/mdatp_managed.json
   state: absent
  when: mdatp_managed.stat.exists
 
- name: Copying new configuration file into /etc/opt/microsoft/mdatp/managed/
  copy:
   src: /etc/ansible/files/mdatp_managed.json
   dest: /etc/opt/microsoft/mdatp/managed/
   mode: 0600
   owner: root
   group: root
   
- name: Restarting MDATP service
  shell: systemctl restart mdatp
